server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Tell browsers and Cloudflare not to cache game files
    location ~* \.(html|js|css)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }
}
